# Generated by Django 2.2b1 on 2019-03-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='name',
        ),
    ]
